<a href="https://colab.research.google.com/github/XanOlazcuagaGaribal/python/blob/main/NumpyExo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [2]:
import numpy as  np

#### Q2 : Afficher la version de numpy et la configuration 

In [ ]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### Q3 : Créer un vecteur nul de taille 10

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [ ]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [ ]:
z = np.arange(10,50,1)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [ ]:
z = np.flip(z)
#z=z[::1]
z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [ ]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [ ]:
B = np.eye(3)
B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [ ]:
A = np.random.randint(0,8, size=(3, 3, 3))
A

array([[[3, 6, 0],
        [1, 3, 1],
        [3, 2, 3]],

       [[6, 2, 1],
        [4, 7, 6],
        [1, 3, 0]],

       [[3, 2, 5],
        [0, 5, 3],
        [6, 2, 2]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [ ]:
D = np.random.randint(50, size=(3, 3))
print(D)
print('Min : ',D.min())
print('Max : ',D.max())

[[34 14 31]
 [ 7  4 19]
 [13 11 45]]
Min :  4
Max :  45


#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [26]:
np.diag(np.array([1,2,3,4]),-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [ ]:
from random import randint
F = np.random.randint(10,size=5)
print(F.sum())
F

27


array([1, 9, 8, 4, 5])

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [ ]:
from random import randint
F = np.random.randint(10,size=5)
print(F.mean())
F

3.6


array([9, 3, 1, 4, 1])

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [11]:
l = [x for x in range(11)]
print(l)
np.size(l)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [42]:
#i = np.arange(0.1,1,0.1)
i = np.linspace(0,1,11,False)[1:]
i

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [44]:
from random import randint
A = np.random.randint(10,size=5)
B = np.random.randint(10,size=5)
print(A)
print(B)
np.array_equal(A,A)

[1 1 6 1 2]
[5 8 5 4 8]


True

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [ ]:
float_array = np.arange(2, 10, dtype=float)
print(float_array)
int_array = float_array.astype(int)
print(int_array)

[2. 3. 4. 5. 6. 7. 8. 9.]
[2 3 4 5 6 7 8 9]


#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [45]:
M = np.random.randint(50, size=(5, 5))
print(M)
norm = np.linalg.norm(M)
norm_array = M/norm
print(norm_array)

#M = (M - np.mean(M)) / (np.std(M))


[[ 4  6 37 38 14]
 [ 4 28  2 21 47]
 [ 4  0 32 45 27]
 [ 9 27 45 40 12]
 [34  7  9 32 22]]
[[0.03008114 0.04512171 0.27825055 0.28577083 0.10528399]
 [0.03008114 0.21056798 0.01504057 0.15792599 0.3534534 ]
 [0.03008114 0.         0.24064912 0.33841283 0.2030477 ]
 [0.06768257 0.2030477  0.33841283 0.30081141 0.09024342]
 [0.25568969 0.052642   0.06768257 0.24064912 0.16544627]]


#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [48]:
M = np.random.randint(50, size=(2, 2))
print(M)
M.transpose()

[[37 49]
 [19  9]]


array([[37, 19],
       [49,  9]])

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

In [57]:
import random
n = 10
p = 1
M = np.zeros((n,n))
np.put(M,np.random.choice(range(n*n),p,replace=False),1)
print(M)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)

In [52]:
M = np.random.randint(50, size=(5,5,3))
M2 = np.random.randint(50, size=(5,5))
print(M*M2[:,:,None])

[[[  16    1   33]
  [1426  124  279]
  [1053  324 1215]
  [  21  287    0]
  [  10   70  480]]

 [[ 640  208  320]
  [1350 2070 1530]
  [ 546  966  483]
  [ 957  348  986]
  [1702  148  555]]

 [[   0    0    0]
  [ 920  920   23]
  [ 672  896 1056]
  [ 168   96   30]
  [1012 1452 1716]]

 [[1376   64  672]
  [  46    2   45]
  [ 299  483  299]
  [ 800  420  220]
  [ 248  775  403]]

 [[  99  102   87]
  [ 104  192  344]
  [ 624 1833  507]
  [ 133  741  418]
  [2162 2021 1739]]]
