<a href="https://colab.research.google.com/github/XanOlazcuagaGaribal/python/blob/main/suiteAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problème : Coefficients binomiaux

$(_k^n) = C_k^n = \frac{n!}{k! (n - k)!}$

n <- input(user)

k <- input(user)

On défini la fonction factorielle 
>Si n < 2 

> > Alors on affiche 1

> Sinon 

> > On affiche n * fact(n-1)

C <- (fact(n)) / (fact(k) * fact(n-k))


In [1]:
from math import factorial
n = int(input())
k = int(input())
c = 0
def fact(n):
  if n < 2 :
    return 1
  else :
     return n*fact(n-1)

c = fact(n) / (fact(k)*(fact(n-k)))

print(c)

#import scipy.special
#scipy.special.binom(10, 5)

2
5
0.016666666666666666


Problème : Saisie de matrice 

On défini la fonction qui demande à l'utilisateur la taille d'un matrice

mat <- []

lignes <- input(user)

colonnes <- input(user)

mat = np.zeros((lignes,colonnes))

On renvoie la matrice

//Saisi de la matrice 

Pour j dans colonnes

> Pour i dans lignes

> > mat[i,j] = input(user)



In [17]:
import numpy as np

mat = []
lignes = int(input("Lignes : "))
colonnes = int(input("Colonnes : "))
mat = np.zeros((lignes,colonnes))

for j in range(0, colonnes):
  for i in range(0,lignes):
    mat[i,j] = input("Valeur : ")

print(mat)

Lignes : 2
Colonnes : 2
Valeur : 1
Valeur : 2
Valeur : 3
Valeur : 4
[[1. 3.]
 [2. 4.]]


Problème : Multiplication matricielle

1- On défini un fonction permettant de saisir une matrice

mat <- []

lignes <- input(user)

colonnes <- input(user)

mat = np.zeros((lignes,colonnes))

def matrice():

> //Saisi de la matrice 

> Pour j dans colonnes

> > Pour i dans lignes

> > > mat[i,j] = input(user)

On appelle la fonction 2 fois 

A <- matrice()

print(A)

B <- matrice()

print(B)

---

3 - Multiplication matricielle 

> $C_{ij} = \sum_{k=1}^m a_{ik} * b_{kj}$

nouvelleMatrice <- []



On affiche la matrice en résultat

In [26]:
import numpy as np

mat = []
lignes = int(input("Lignes : "))
colonnes = int(input("Colonnes : "))
mat = np.zeros((lignes,colonnes))
def matrice():
  for j in range(0, colonnes):
    for i in range(0,lignes):
      mat[i,j] = input("Valeur : [" + str(i) +" , " + str(j) + "]")
  return mat
A = matrice()
print(A)
B = matrice()
print(B)
nouvelleMatrice = []

for i in range(len(A)):
    ligne = []
    for j in range(len(B[0])):
      element = 0
      for k in range(len(A[0])):
        element = element + A[i][k] * B[k][j]
      ligne.append(element)
    nouvelleMatrice.append(ligne)
print(nouvelleMatrice)
#multiplication matricielle 
#def produitMatriciel(A, B):
#    n = len(A)
#    p = len(A[0])
#    q = len(B[0])
#    return list([sum([A[i][k]*B[k][j] for k in range(p)]) for j in range(q)] for i in range(n))
#np.dot(A,B)

Lignes : 2
Colonnes : 2
Valeur : [0 , 0]2
Valeur : [1 , 0]2
Valeur : [0 , 1]2
Valeur : [1 , 1]2
[[2. 2.]
 [2. 2.]]
Valeur : [0 , 0]2
Valeur : [1 , 0]2
Valeur : [0 , 1]2
Valeur : [1 , 1]2
[[2. 2.]
 [2. 2.]]
[[8.0, 8.0], [8.0, 8.0]]
